#!/bin/bash

prefix="$1"

if [[ -z $prefix ]]; then
    prefix="/usr/local/"
fi

mkdir -p "$prefix/bin" "$prefix/share/man/man1"
cp "dsort" "$prefix/bin/dsort"
cp "dsort.1" "$prefix/share/man/man1/dsort.1"
